// frontend/src/components/AuthScreen.vue
<template>
  <main class="auth-screen">
    <section class="auth-card auth-brief-shell" aria-label="Agno AIOS 认证入口">
      <aside class="auth-brief" aria-label="平台入口信息">
        <header class="auth-brief-header">
          <div class="auth-brand">
            <span class="auth-logo">
              <el-icon><Platform /></el-icon>
            </span>
            <div>
              <h1>Agno</h1>
              <p>AIOS</p>
            </div>
          </div>

          <button
            type="button"
            class="theme-chip"
            :aria-label="isDark ? '切换到浅色模式' : '切换到深色模式'"
            @click="$emit('toggle-theme')"
          >
            <el-icon>
              <Sunny v-if="isDark" />
              <Moon v-else />
            </el-icon>
          </button>
        </header>

        <div class="auth-brief-title">
          <span>AGENT CONTROL</span>
          <h2>Agno AIOS</h2>
          <p>登录后继续使用 Chat、MCP、Trace 与模型设置。</p>
        </div>

        <div class="auth-brief-grid">
          <span v-for="item in briefItems" :key="item.label" :class="item.tone">
            <el-icon><component :is="item.icon" /></el-icon>
            {{ item.label }}
          </span>
        </div>
      </aside>

      <div class="auth-panel">
        <div class="auth-panel-heading">
          <span>{{ mode === 'login' ? 'SIGN IN' : 'CREATE' }}</span>
          <h2>{{ mode === 'login' ? '进入工作台' : '创建账号' }}</h2>
        </div>

        <div class="auth-tabs" role="tablist" aria-label="认证方式">
          <button
            type="button"
            :class="{ active: mode === 'login' }"
            role="tab"
            :aria-selected="mode === 'login'"
            @click="mode = 'login'"
          >
            登录
          </button>
          <button
            type="button"
            :class="{ active: mode === 'register' }"
            role="tab"
            :aria-selected="mode === 'register'"
            @click="mode = 'register'"
          >
            注册
          </button>
        </div>

        <form class="auth-form" @submit.prevent="submitAuth">
          <label class="auth-field">
            <span>邮箱</span>
            <el-input
              v-model="email"
              autocomplete="email"
              clearable
              placeholder="operator@example.com"
              size="large"
            />
          </label>

          <label class="auth-field">
            <span>密码</span>
            <el-input
              v-model="password"
              autocomplete="current-password"
              placeholder="至少 8 位"
              show-password
              size="large"
              type="password"
            />
          </label>

          <el-alert
            v-if="errorMessage"
            :title="errorMessage"
            class="auth-alert"
            show-icon
            type="error"
          />

          <el-button
            class="auth-submit"
            native-type="submit"
            size="large"
            type="primary"
            :loading="submitting"
          >
            {{ mode === 'login' ? '进入 Agno AIOS' : '创建并进入' }}
          </el-button>
        </form>

        <div v-if="oauthProviders.length" class="auth-oauth">
          <span>OAuth</span>
          <div>
            <el-button
              v-for="provider in oauthProviders"
              :key="provider"
              class="oauth-button"
              :loading="oauthLoading === provider"
              @click="startOAuth(provider)"
            >
              {{ providerLabel(provider) }}
            </el-button>
          </div>
        </div>

        <div class="auth-footer">
          <span>JWT</span>
          <span>PgVector</span>
          <span>MCP</span>
        </div>
      </div>
    </section>
  </main>
</template>

<script setup lang="ts">
import { onMounted, ref, type Component } from 'vue'
import { ChatDotRound, Connection, DataAnalysis, Moon, Platform, Sunny } from '@element-plus/icons-vue'
import {
  clearStoredAuthToken,
  fetchCurrentUser,
  fetchOAuthProviders,
  loginWithPassword,
  registerWithPassword,
  requestOAuthAuthorization,
  storeAuthToken,
} from '../lib/authClient'
import type { AuthUser, OAuthProvider } from '../types'

defineProps<{
  isDark: boolean
}>()

const emit = defineEmits<{
  authenticated: [user: AuthUser]
  'toggle-theme': []
}>()

type AuthMode = 'login' | 'register'
type BriefItem = {
  label: string
  tone: string
  icon: Component
}

const mode = ref<AuthMode>('login')
const email = ref('')
const password = ref('')
const submitting = ref(false)
const errorMessage = ref('')
const oauthProviders = ref<OAuthProvider[]>([])
const oauthLoading = ref<OAuthProvider | ''>('')

const briefItems: BriefItem[] = [
  { label: 'Chat', tone: 'blue', icon: ChatDotRound },
  { label: 'MCP', tone: 'yellow', icon: Connection },
  { label: 'Trace', tone: 'green', icon: DataAnalysis },
  { label: 'Model', tone: 'red', icon: Platform },
]

const validate = () => {
  const normalizedEmail = email.value.trim()
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail)) {
    errorMessage.value = '请输入有效邮箱'
    return null
  }
  if (password.value.length < 8) {
    errorMessage.value = '密码至少需要 8 位'
    return null
  }
  return { email: normalizedEmail, password: password.value }
}

const submitAuth = async () => {
  const credentials = validate()
  if (!credentials) return

  submitting.value = true
  errorMessage.value = ''
  try {
    if (mode.value === 'register') {
      await registerWithPassword(credentials)
    }
    const token = await loginWithPassword(credentials)
    storeAuthToken(token.access_token)
    const user = await fetchCurrentUser(token.access_token)
    emit('authenticated', user)
  } catch (err: unknown) {
    clearStoredAuthToken()
    errorMessage.value = err instanceof Error && err.message ? err.message : '认证失败'
  } finally {
    submitting.value = false
  }
}

const providerLabel = (provider: OAuthProvider) => {
  const labels: Record<string, string> = {
    github: 'GitHub',
    google: 'Google',
    microsoft: 'Microsoft',
  }
  return labels[provider] || provider
}

const startOAuth = async (provider: OAuthProvider) => {
  oauthLoading.value = provider
  errorMessage.value = ''
  try {
    const authorizationUrl = await requestOAuthAuthorization(provider)
    window.location.assign(authorizationUrl)
  } catch (err: unknown) {
    errorMessage.value = err instanceof Error && err.message ? err.message : 'OAuth 授权失败'
  } finally {
    oauthLoading.value = ''
  }
}

onMounted(async () => {
  try {
    oauthProviders.value = await fetchOAuthProviders()
  } catch {
    oauthProviders.value = []
  }
})
</script>

<style scoped>
.auth-screen {
  display: grid;
  min-height: 100dvh;
  place-items: center;
  padding: 20px;
  background:
    linear-gradient(90deg, rgba(92, 105, 124, 0.08) 1px, transparent 1px),
    linear-gradient(180deg, rgba(92, 105, 124, 0.06) 1px, transparent 1px),
    var(--ag-page);
  background-size: 34px 34px;
  color: var(--ag-text);
}

.auth-card {
  display: grid;
  width: min(980px, 100%);
  min-height: min(620px, calc(100dvh - 40px));
  grid-template-columns: minmax(300px, 0.72fr) minmax(340px, 1fr);
  overflow: hidden;
  border: 1px solid var(--ag-border);
  border-radius: 8px;
  background: var(--ag-frame);
  box-shadow: var(--ag-shadow);
}

.auth-brief,
.auth-panel {
  min-width: 0;
  padding: clamp(22px, 4vw, 38px);
}

.auth-brief {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 32px;
  border-right: 1px solid var(--ag-border);
  background: var(--ag-sidebar);
  color: var(--ag-sidebar-text);
}

.auth-brief-header,
.auth-brand {
  display: flex;
  align-items: center;
}

.auth-brief-header {
  justify-content: space-between;
  gap: 16px;
}

.auth-brand {
  gap: 12px;
}

.auth-logo {
  display: grid;
  width: 38px;
  height: 38px;
  place-items: center;
  border: 1px solid var(--ag-sidebar-border);
  border-radius: 8px;
  background: var(--ag-sidebar-icon);
  color: var(--ag-accent);
}

.auth-brand h1,
.auth-brand p,
.auth-panel-heading h2,
.auth-brief-title h2,
.auth-brief-title p {
  margin: 0;
}

.auth-brand h1 {
  color: var(--ag-sidebar-strong);
  font-size: 17px;
  font-weight: 780;
}

.auth-brand p {
  margin-top: 2px;
  color: var(--ag-sidebar-muted);
  font-family: "JetBrains Mono", "Fira Code", monospace;
  font-size: 10px;
  font-weight: 800;
}

.theme-chip {
  display: grid;
  width: 36px;
  height: 36px;
  place-items: center;
  border: 1px solid var(--ag-sidebar-border);
  border-radius: 8px;
  background: var(--ag-sidebar-icon);
  color: var(--ag-sidebar-text);
}

.auth-brief-title span,
.auth-panel-heading span {
  display: block;
  color: var(--ag-accent);
  font-family: "JetBrains Mono", "Fira Code", monospace;
  font-size: 11px;
  font-weight: 800;
}

.auth-brief-title h2 {
  margin-top: 10px;
  color: var(--ag-sidebar-strong);
  font-size: clamp(34px, 5vw, 54px);
  font-weight: 840;
  line-height: 0.98;
}

.auth-brief-title p {
  max-width: 360px;
  margin-top: 14px;
  color: var(--ag-sidebar-muted);
  font-size: 13px;
  line-height: 1.7;
}

.auth-brief-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
}

.auth-brief-grid span {
  display: inline-flex;
  min-height: 42px;
  align-items: center;
  gap: 8px;
  border: 1px solid var(--ag-sidebar-border);
  border-radius: 8px;
  background: var(--ag-sidebar-item);
  padding: 0 12px;
  color: var(--ag-sidebar-strong);
  font-family: "JetBrains Mono", "Fira Code", monospace;
  font-size: 12px;
  font-weight: 800;
}

.auth-brief-grid .blue {
  color: var(--ag-blue);
}

.auth-brief-grid .green {
  color: var(--ag-green);
}

.auth-brief-grid .yellow {
  color: var(--ag-yellow);
}

.auth-brief-grid .red {
  color: var(--ag-accent);
}

.auth-panel {
  display: flex;
  flex-direction: column;
  justify-content: center;
  background: var(--ag-panel);
}

.auth-panel-heading h2 {
  margin-top: 8px;
  color: var(--ag-heading);
  font-size: 28px;
  font-weight: 820;
}

.auth-tabs {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 4px;
  margin-top: 28px;
  border: 1px solid var(--ag-border);
  border-radius: 8px;
  background: var(--ag-panel-soft);
  padding: 4px;
}

.auth-tabs button {
  min-height: 38px;
  border-radius: 6px;
  color: var(--ag-muted);
  font-size: 13px;
  font-weight: 750;
}

.auth-tabs button.active {
  background: var(--ag-panel-raised);
  color: var(--ag-heading);
  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.08);
}

.auth-form {
  display: grid;
  gap: 16px;
  margin-top: 22px;
}

.auth-field {
  display: grid;
  gap: 8px;
}

.auth-field > span,
.auth-oauth > span {
  color: var(--ag-muted-strong);
  font-size: 12px;
  font-weight: 750;
}

.auth-alert {
  margin: 0;
}

.auth-submit {
  width: 100%;
}

.auth-oauth {
  display: grid;
  gap: 10px;
  margin-top: 20px;
}

.auth-oauth > div {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.oauth-button {
  min-width: 104px;
}

.auth-footer {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 22px;
}

.auth-footer span {
  display: inline-flex;
  align-items: center;
  border: 1px solid var(--ag-border);
  border-radius: 6px;
  background: var(--ag-panel-soft);
  padding: 3px 7px;
  color: var(--ag-muted);
  font-family: "JetBrains Mono", "Fira Code", monospace;
  font-size: 10px;
  font-weight: 800;
}

@media (max-width: 820px) {
  .auth-screen {
    place-items: stretch;
    padding: 12px;
  }

  .auth-card {
    min-height: calc(100dvh - 24px);
    grid-template-columns: 1fr;
  }

  .auth-brief {
    border-right: 0;
    border-bottom: 1px solid var(--ag-border);
  }
}

@media (max-width: 520px) {
  .auth-brief,
  .auth-panel {
    padding: 20px;
  }

  .auth-brief-grid {
    grid-template-columns: 1fr;
  }
}
</style>

// frontend-react/src/features/auth/auth-screen.tsx
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import {
  ArrowRight,
  Github,
  KeyRound,
  LoaderCircle,
  LockKeyhole,
  Mail,
  ShieldCheck,
} from 'lucide-react'

import { Button } from '#/components/ui/button.tsx'
import { Input } from '#/components/ui/input.tsx'
import { Label } from '#/components/ui/label.tsx'
import { fetchOAuthProviders, requestOAuthAuthorization } from '#/lib/auth.ts'
import type { OAuthProvider } from '#/lib/auth.ts'
import { cn } from '#/lib/utils.ts'

import { useAuth } from './auth-provider.tsx'

type AuthMode = 'login' | 'register'

const providerLabels: Record<string, string> = {
  github: 'GitHub',
  google: 'Google',
  microsoft: 'Microsoft',
}

function providerLabel(provider: OAuthProvider) {
  return providerLabels[provider] ?? provider
}

export function AuthScreen() {
  const auth = useAuth()
  const [mode, setMode] = useState<AuthMode>('login')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [notice, setNotice] = useState<string | null>(null)
  const [providers, setProviders] = useState<OAuthProvider[]>([])
  const [pendingProvider, setPendingProvider] = useState<string | null>(null)
  const [isSubmitting, setSubmitting] = useState(false)

  useEffect(() => {
    let cancelled = false
    void fetchOAuthProviders().then((nextProviders) => {
      if (!cancelled) setProviders(nextProviders)
    })
    return () => {
      cancelled = true
    }
  }, [])

  const isRegister = mode === 'register'

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setNotice(null)
    setSubmitting(true)
    void (async () => {
      try {
        if (isRegister) {
          await auth.register(email, password)
        } else {
          await auth.login(email, password)
        }
      } catch (error) {
        setNotice(error instanceof Error ? error.message : '认证请求失败。')
      } finally {
        setSubmitting(false)
      }
    })()
  }

  async function startOAuth(provider: OAuthProvider) {
    setNotice(null)
    setPendingProvider(provider)
    try {
      const authorizationUrl = await requestOAuthAuthorization(provider)
      window.location.assign(authorizationUrl)
    } catch (error) {
      setNotice(
        error instanceof Error ? error.message : 'OAuth 授权初始化失败。',
      )
      setPendingProvider(null)
    }
  }

  return (
    <main className="min-h-dvh overflow-hidden bg-[#071014] text-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_18%,rgba(56,189,248,0.22),transparent_28%),radial-gradient(circle_at_82%_12%,rgba(16,185,129,0.16),transparent_24%),linear-gradient(135deg,#071014_0%,#0d1821_52%,#eef4f8_52%,#f8fafc_100%)]" />
      <div className="relative grid min-h-dvh grid-cols-1 lg:grid-cols-[minmax(0,1fr)_480px]">
        <section className="hidden min-h-0 flex-col justify-between p-10 lg:flex">
          <div className="flex items-center gap-3">
            <div className="grid size-11 place-items-center rounded-xl border border-cyan-200/20 bg-cyan-200/10 text-cyan-100">
              <ShieldCheck className="size-5" />
            </div>
            <div>
              <div className="text-xs font-semibold tracking-[0.28em] text-cyan-100/68 uppercase">
                AGNO AIOS
              </div>
              <div className="text-lg font-black tracking-[-0.03em]">
                AI 信息安全中台
              </div>
            </div>
          </div>

          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 rounded-full border border-cyan-200/15 bg-white/[0.04] px-3 py-1 text-xs text-cyan-100/72">
              <KeyRound className="size-3.5" />
              FastAPI Users JWT / OAuth2
            </div>
            <h1 className="mt-8 max-w-4xl text-[clamp(3rem,4.6vw,5.2rem)] leading-[0.98] font-black tracking-[-0.07em]">
              <span className="block">登录后进入</span>
              <span className="block">安全运营工作台</span>
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300/78">
              认证层对齐后端 FastAPI Users，统一承接账号注册、JWT 登录以及
              GitHub / Google / Microsoft OAuth2 登录入口。
            </p>
          </div>

          <div className="grid max-w-3xl grid-cols-3 gap-3">
            {['Agent 对话', 'Trace 观测', 'MCP 工具'].map((item) => (
              <div
                className="rounded-2xl border border-white/10 bg-slate-950/78 p-4 text-white shadow-[0_18px_50px_rgba(0,0,0,0.24)] backdrop-blur"
                key={item}
              >
                <div className="text-sm font-semibold text-white">{item}</div>
                <div className="mt-2 h-1 rounded-full bg-cyan-200/45" />
              </div>
            ))}
          </div>
        </section>

        <section className="flex min-h-dvh items-center justify-center p-4 sm:p-8">
          <div className="w-full max-w-[440px] rounded-[2rem] border border-slate-200 bg-white p-5 text-slate-950 shadow-[0_24px_80px_rgba(15,23,42,0.18)] sm:p-7">
            <div className="lg:hidden">
              <div className="flex items-center gap-3">
                <div className="grid size-10 place-items-center rounded-xl bg-slate-950 text-white">
                  <ShieldCheck className="size-4.5" />
                </div>
                <div>
                  <div className="text-xs font-semibold tracking-[0.22em] text-slate-500 uppercase">
                    AGNO AIOS
                  </div>
                  <div className="font-black">AI 信息安全中台</div>
                </div>
              </div>
            </div>

            <div className="mt-6 flex rounded-xl border border-slate-200 bg-slate-50 p-1 lg:mt-0">
              {(['login', 'register'] as const).map((item) => (
                <button
                  className={cn(
                    'h-10 flex-1 rounded-lg text-sm font-semibold transition-colors',
                    mode === item
                      ? 'bg-slate-950 text-white shadow-sm'
                      : 'text-slate-500 hover:text-slate-950',
                  )}
                  key={item}
                  onClick={() => {
                    setMode(item)
                    setNotice(null)
                  }}
                  type="button"
                >
                  {item === 'login' ? '登录' : '注册'}
                </button>
              ))}
            </div>

            <div className="mt-7">
              <h2 className="text-3xl font-black tracking-[-0.05em]">
                {isRegister ? '创建账号' : '欢迎回来'}
              </h2>
              <p className="mt-2 text-sm leading-6 text-slate-500">
                {isRegister
                  ? '密码至少 8 位，注册成功后会自动登录。'
                  : '使用邮箱和密码登录后进入 AI 信息安全中台。'}
              </p>
            </div>

            <form className="mt-6 flex flex-col gap-4" onSubmit={submit}>
              <div className="flex flex-col gap-2">
                <Label htmlFor="auth-email">邮箱</Label>
                <div className="relative">
                  <Mail className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" />
                  <Input
                    autoComplete="email"
                    className="h-11 pl-9"
                    id="auth-email"
                    onChange={(event) => setEmail(event.target.value)}
                    placeholder="secops@example.com"
                    required
                    type="email"
                    value={email}
                  />
                </div>
              </div>

              <div className="flex flex-col gap-2">
                <Label htmlFor="auth-password">密码</Label>
                <div className="relative">
                  <LockKeyhole className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-slate-400" />
                  <Input
                    autoComplete={
                      isRegister ? 'new-password' : 'current-password'
                    }
                    className="h-11 pl-9"
                    id="auth-password"
                    minLength={8}
                    onChange={(event) => setPassword(event.target.value)}
                    placeholder="至少 8 位"
                    required
                    type="password"
                    value={password}
                  />
                </div>
              </div>

              {notice ? (
                <div className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">
                  {notice}
                </div>
              ) : null}

              <Button
                className="h-11 rounded-xl bg-slate-950 text-white hover:bg-slate-800"
                disabled={isSubmitting}
                type="submit"
              >
                {isSubmitting ? (
                  <LoaderCircle className="size-4 animate-spin" />
                ) : (
                  <ArrowRight className="size-4" />
                )}
                {isRegister ? '注册并进入' : '登录中台'}
              </Button>
            </form>

            <div className="mt-6 border-t border-slate-200 pt-5">
              <div className="text-center text-xs font-medium text-slate-400">
                OAuth2 登录
              </div>
              <div className="mt-3 grid gap-2">
                {providers.length ? (
                  providers.map((provider) => (
                    <Button
                      className="h-10 rounded-xl"
                      disabled={pendingProvider !== null}
                      key={provider}
                      onClick={() => void startOAuth(provider)}
                      type="button"
                      variant="outline"
                    >
                      <Github className="size-4" />
                      使用 {providerLabel(provider)} 登录
                    </Button>
                  ))
                ) : (
                  <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 px-3 py-3 text-center text-xs leading-5 text-slate-500">
                    后端未配置 OAuth Provider 时，仅显示邮箱密码登录。
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
      </div>
    </main>
  )
}
